### ISSUE TITLE
Upgrade stock and custom AMIs to Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by senderista** [uwescience/myria-ec2-ansible#35]
This is the next LTS release and hopefully will have some performance enhancements that we can benefit from (like ZFS if we want to benchmark vs. ext4). AMI IDs are available at https://cloud-images.ubuntu.com/locator/ec2/.

**Comment by senderista** [comment]
Ubuntu 16.04 no longer includes Python 2 by default, so we need to install it before running any more Ansible modules: https://gist.github.com/gwillem/4ba393dceb55e5ae276a87300f6b8e6f#file-ansible-bootstrap-ubuntu-16-04-yml

```
- hosts: all
  gather_facts: False

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
```
